ept/urls.py
from django.contrib import admin
from django.urls import path, include
from manager.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("manager.urls")),
    path('admin/', admin.site.urls),
    path("user/", include("userauths.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from manager import views

app_name = "manager"

urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/transactions", views.transactions, name="transactions"),
    path("dashboard/add-transaction", views.addTransaction, name="add-transaction"),
    path("dashboard/delete-transaction", views.deleteTransaction, name="delete-transaction"),
    path("dashboard/wallet", views.wallet, name="wallet"),
    path("dashboard/create-wallet", views.walletCreation, name="create-wallet"),
    path("dashboard/update-wallet", views.updateWallet, name="update-wallet"),
    path("dashboard/delete-wallet", views.deleteWallet, name="delete-wallet"),
    path("dashboard/generate-statement", views.generateStatement, name="generate-statement"),
]

userauths/urls.py
from django.urls import path, include
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.registerView, name="sign-up"),
    path("sign-in/", views.loginView, name="sign-in"),
    path("sign-out/", views.logoutView, name="sign-out"),
]

manager/models.py
from django.db import models
from userauths.models import User
from django.utils import timezone

# Create your models he

class Wallet(models.Model):
    CURRENCY = (
        ('USD', 'Dollar'),
        ('EUR', 'Euro'),
        ('GBP', 'Pounds'),
        ('BRL', 'Brazilian real'),
        ('JPY', 'Japanese yen'),
    )
    
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    balance = models.DecimalField(null=False, max_digits=10, decimal_places=2, editable=True)
    monthlyIncome = models.DecimalField(max_digits=7, decimal_places=2, editable=True)
    currencyType = models.CharField(max_length=3, null=False, choices=CURRENCY)
    

    def __str__(self):
        return str(self.balance)
    
class Transaction(models.Model):
    wallet = models.ForeignKey('Wallet', on_delete=models.CASCADE, null=False)
    value = models.DecimalField(null=False, max_digits=10, decimal_places=2)
    date = models.DateField(default=timezone.now)
    description = models.TextField(max_length=100)
    

    def __str__(self):
        return str(self.value)

manager/forms.py
from django import forms
from django.forms import DateTimeInput, DateField
from .models import *

class WalletCreationForm(forms.Form):
    currency = forms.ChoiceField(choices=Wallet.CURRENCY)
    income = forms.DecimalField(max_digits=7, decimal_places=2)
    balance = forms.DecimalField(max_digits=10, decimal_places=2)

class WalletUpdateForm(forms.ModelForm):
    class Meta:
        model = Wallet
        fields = ['balance', 'monthlyIncome', 'currencyType']
    
class TransactionCreationForm(forms.Form):
    value = forms.DecimalField(max_digits=10, decimal_places=2)
    date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'rows':3}))

class TransactionEditForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['value', 'date', 'description']

manager/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from manager.forms import *
from manager.models import Wallet, Transaction
from django.contrib import messages
from django.http import JsonResponse, FileResponse
from reportlab.pdfgen import canvas
from io import BytesIO
# Create your views here.

def index(request):
    return render(request, 'manager/index.html')

@login_required(login_url='sign-in/')
def dashboard(request):
    return render(request, 'dashboard/dashboard.html')

@login_required(login_url='sign-in/')
def transactions(request):
    userWallet = Wallet.objects.get(owner=request.user)
    if userWallet:
        transactions = Transaction.objects.filter(wallet=userWallet)
    else:
        transactions = []

    context = {'transactions':transactions}

    return render(request, 'dashboard/transactions.html', context)

@login_required(login_url='sign-in/')
def wallet(request):
    return render(request, 'dashboard/wallet.html')

@login_required(login_url='sign-in/')
def walletCreation(request):
    if request.method == 'POST':
        form = WalletCreationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            wallet = Wallet(balance = data['balance'], monthlyIncome = data['income'], currencyType = data['currency'])
            wallet.owner = request.user
            wallet.save()
            messages.success(request, f"Wallet sucessfully created!")
    else:
        form = WalletCreationForm()
    context = {'form':form}

    return render(request, 'dashboard/create-wallet.html', context)

@login_required(login_url='sign-in/')
def updateWallet(request):
    wallet = get_object_or_404(Wallet, owner = request.user)
    if request.method == "POST":
        form = WalletUpdateForm(request.POST, instance = wallet)
        if form.is_valid():
            form.save()
            messages.success(request, f"The wallet was sucessfully updated.")
        else:
            messages.error(request, f"There was an error, try again.")
    else:
        form = WalletUpdateForm(instance=wallet)

    context = {'form':form, 'wallet':wallet}

    return render(request, 'dashboard/update-wallet.html', context)

@login_required(login_url="sign-in/")
def deleteWallet(request):
    wallet = get_object_or_404(Wallet, owner=request.user)
    if request.method == "POST":
        wallet.delete()
        messages.success(request, f"Your wallet was sucessfully deleted.")
        return redirect('manager:wallet')

    return render(request, 'dashboard/delete-wallet.html')

@login_required(login_url="sign-in/")
def addTransaction(request):
    if request.method == "POST":
        form = TransactionCreationForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = request.user
            usrWallet, created = Wallet.objects.get_or_create(owner= user)
            if created:
                messages.warning(request, f"A new wallet was created.")
            transaction = Transaction(wallet=usrWallet, value=data['value'], date=data['date'], description=data['description'])
            transaction.save()
            messages.success(request, f"Transaction sucessfully added.")
            redirect('dashboard/transaction.html')
    else:
        form = TransactionCreationForm()

    context = {'form':form}

    return render(request, 'dashboard/add-transaction.html', context)

@login_required(login_url='sign-in/')
@require_POST
def deleteTransaction(request):
    transactionId = request.POST.get('transactionId')
    if transactionId:
        try:
            transaction = Transaction.objects.get(pk=transactionId)
            transaction.delete()
            return JsonResponse({'success': True, 'message': 'Transaction successfully deleted.'})
        except Transaction.DoesNotExist:
            return JsonResponse({'success': False, 'message': 'Transaction does not exist.'})
        
    return JsonResponse({'success': False, 'message': 'Invalid request.'})

@login_required(login_url='sign-in/')
def generateStatement(request):
    response = FileResponse(generateStatementFile(), as_attachment=True, filename='user_statement.pdf')

    return response

def generateStatementFile():
    buffer = BytesIO()
    file = canvas.Canvas(buffer)
    transactions = Transaction.objects.all()
    file.drawString(100, 750, "Transaction history")
    y = 700

    for transaction in transactions:
        file.drawString(100, y, f"Value: {transaction.value}")
        file.drawString(100, y - 20, f"Date: {transaction.date}")
        file.drawString(100, y - 40, f"Description: {transaction.description}")
        y -= 80

    file.showPage()
    file.save()
    buffer.seek(0)

    return buffer

templates/manager/index.html
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head class="landing">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets\css\style.css' %}">
    <title>Expenses Tracker - EPT</title>
</head>
<body class="landing">
    <header class="landing">
        <div class="box-img-header landing">
            <img class="img-logo landing" src="{% static 'assets\imgs\logo.png' %}" alt="Logo EPT">
        </div>
        <nav class="landing">
            <a href="#start" class="nav-links landing">Start</a>
            <a href="#info" class="nav-links landing">Learn more</a>
            <a href="#getting-started" class="nav-links landing">Getting started</a>
            <a href="#contact" class="nav-links landing">Contacts</a>
        </nav>
        <div class="box-btn-actions landing">
            <a href="{% url "userauths:sign-up" %}">
                <button class="btn-action landing">Register</button>
            </a>
            <a href="{% url "userauths:sign-in" %}">
                <button class="btn-action landing">Login</button>
            </a>
        </div>
    </header>

    <main class="landing">
        <section class="first-section landing">
            <div class="landing">
                <h1 class="landing">Welcome to <br> <strong class="landing">EPT</strong> </h1>
                <p class="landing">The web app that will help you with your <strong class="landing">savings</strong> and future plans.</p>
                <a class="btn-action link-action landing" href="#info">Learn more</a>
            </div>
            <div class="box-img-main landing">
                <img class="img-main landing" src="{% static 'assets\imgs\main-img.png' %}" alt="Main IMG">
            </div>
        </section>

        <section id="info" class="second-section landing">
            <h2 class="title landing">Learn more</h2>
            <div class="landing">
                <br>
                <p class="landing">
                    Welcome to EPT, your comprehensive web platform for efficient expense management and tracking. EPT, short for Expense Tracker, is built on Django and designed to simplify the process of recording and monitoring your expenditures.
                    With EPT, you can effortlessly log all your financial transactions, providing a centralized hub to manage your expenses seamlessly. What sets EPT apart is its ability to generate detailed monthly summaries, allowing you to gain valuable insights into your spending patterns over time.
                    Visualizing your financial data is made easy with EPT's intuitive table displays. The platform presents your expense information in clear and organized tables directly on the website, making it convenient for you to analyze, understand, and make informed decisions about your budget.
                    Take control of your finances with EPT – the ultimate tool for expense tracking and management. Sign up for free today and embark on a journey towards financial clarity and stability.
                </p>
            </div>
        </section>

        <section id="getting-started" class="third-section landing">
            <h2 class="title landing">Getting started</h2>
            <div class="landing">
                <p class="landing">
                    Getting started with EPT is quick and easy. To begin your journey towards effective expense management, follow these simple steps:
                </p>
                <br>
                <p class="landing">1. <strong class="landing">Create Your Account:</strong> Click on the "Register" button in the header and fill in your basic information, including your email and name. We value your privacy and only ask for essential details to personalize your experience.</p>
                <br>
                <p class="landing">2. <strong class="landing">Login:</strong> If you've already created an account, click on the "Login" button in the header. Enter your registered email and password to access your EPT dashboard.</p>
                <br>
                <p class="landing">Once logged in, you'll have full access to the powerful features of EPT. Start recording your transactions, generating monthly summaries, and gain control over your financial journey.
                EPT is designed to make expense tracking seamless and hassle-free. No need to provide unnecessary personal information – just your email and name are all we require to help you take charge of your expenses.</p>
                <br>
                <p class="landing">
                    Join EPT today and embark on a path towards financial empowerment. Sign up or log in now to experience the convenience of managing your finances with ease!
                </p>
            </div>
        </section>

    </main>

    <footer id="contact" class="landing">
        <h2 class="title landing">Contacts</h2>
        <div class="landing">
            <!-- atualizar com link do repo quando estiver publico -->
            <a href="https://github.com/kaelkkd/ept" title="GitHub" target="_blank" class="landing">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#fff" class="bi bi-github landing" viewBox="0 0 16 16">
                    <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
                </svg>
            </a>
            <a href="https://www.linkedin.com/in/kaelsiebra/" title="LinkedIn" target="_blank" class="landing">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="#fff" class="bi bi-linkedin landing" viewBox="0 0 16 16">
                    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
                </svg>
            </a>
        </div>
    </footer>
    <script src="{% static 'assets\js\script.js' %}"></script>
</body>
</html>
{% endblock content %}