ept/urls.py
from django.contrib import admin
from django.urls import path, include
from manager.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("manager.urls")),
    path('admin/', admin.site.urls),
    path("user/", include("userauths.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from manager import views

app_name = "manager"

urlpatterns = [
    path("", views.index, name="index"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/transactions", views.transactions, name="transactions"),
    path("dashboard/add-transaction", views.addTransaction, name="add-transaction"),
    path("dashboard/delete-transaction", views.deleteTransaction, name="delete-transaction"),
    path("dashboard/wallet", views.wallet, name="wallet"),
    path("dashboard/create-wallet", views.walletCreation, name="create-wallet"),
    path("dashboard/update-wallet", views.updateWallet, name="update-wallet"),
    path("dashboard/delete-wallet", views.deleteWallet, name="delete-wallet"),
    path("dashboard/generate-statement", views.generateStatement, name="generate-statement"),
]

userauths/urls.py
from django.urls import path, include
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.registerView, name="sign-up"),
    path("sign-in/", views.loginView, name="sign-in"),
    path("sign-out/", views.logoutView, name="sign-out"),
]

templates/dashboard/add-transaction.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div class="main">
    <div class="transactions">

        {% if form.errors %}
        <div class="alert alert-danger">
            <strong>{{ form.errors }}</strong>
        </div>
        {% endif %}

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <div class="transaction-form">
            <form class="t-form" method="POST">
                {% csrf_token %}
                <h2>Insert the transaction information</h2>
                <div class="transaction-form">
                    <label for="value">Value:</label>
                    {{ form.value }}
                </div>
                <div class="transaction-form">
                    <label for="description">Description:</label>
                    {{ form.description }}
                </div>
                <div class="transaction-form">
                    <label for="date">Date:</label>
                    {{ form.date }}
                </div>
                <button type="submit">Add transaction</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'assets\css\dashboard.css' %}">
    <title>Admin panel</title>
</head>

<body>
    <div class="container">
        <div class="topbar">
            <div class="logo">
                <h2>EPT</h2>
            </div>
            <div class="search">
                <input type="text" name="search" placeholder="search here">
                <label for="search"><i class="fas fa-search"></i></label>
            </div>
            <i class="fas fa-bell"></i>
            <div class="user">
                <img src="img/user.png" alt="">
            </div>
        </div>
        <div class="sidebar">
            <ul>
                <li>
                    <a href="{% url "manager:dashboard" %}">
                        <i class="fas fa-th-large"></i>
                        <div>Dashboard</div>
                    </a>
                </li>
                <li>
                    <a href="{% url "manager:transactions" %}">
                        <i class="fas fa-hand-holding-usd"></i>
                        <div>Transactions</div>
                    </a>
                </li>
                <li>
                    <a href="{% url "manager:wallet" %}">
                        <i class="fas fa-wallet"></i>
                        <div>Wallet</div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-question"></i>
                        <div>Help</div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-cog"></i>
                        <div>Settings</div>
                    </a>
                </li>
                <li>
                    <a href="{% url "userauths:sign-out" %}">
                        <i class="fas fa-arrow-from-left"></i>
                        <div>Logout</div>
                    </a>
                </li>
            </ul>
        </div>
        
        {% block content %}

        {% endblock %}
    <script src="{% static 'chart.js@4.4.1/dist/chart.umd.min.js' %}"></script>
    <script src="{% static 'assets\js\chart1.js' %}"></script>
    <script src="{% static 'assets\js\chart2.js' %}"></script>
    <script src="{% static 'assets\js\transactions.js' %}"></script>
</body>

</html>

templates/dashboard/create-wallet.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div class="main">
    <div class="wallet">
        <h1>Hello {{ user.username }}!</h1>
        
        {% if form.errors %}
        <div class="alert alert-danger">
            <strong>{{ form.errors }}</strong>
        </div>
        {% endif %}

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="wallet-form">
            <form class="w-form" method="post">
                {% csrf_token %}
                <h2>Insert your wallet info here</h2>
                <div class="wallet-form">
                    <label for="currency">Currency:</label>
                    {{ form.currency }}
                </div>
                <div class="wallet-form">
                    <label for="income">Monthly Income:</label>
                    {{ form.income }}
                </div>
                <div class="wallet-form">
                    <label for="balance">Balance:</label>
                    {{ form.balance }}
                </div>
                <button type="submit">Create wallet</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/dashboard.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div class="main">
    <div class="cards">
        <div class="card">
            <div class="card-content">
                <div class="number">$1217</div>
                <div class="card-name">Total savings</div>
            </div>
            <div class="icon-box">
                <i class="fas fa-dollar-sign"></i>
            </div>
        </div>
        <div class="card">
            <div class="card-content">
                <div class="number">$42</div>
                <div class="card-name">30-days savings</div>
            </div>
            <div class="icon-box">
                <i class="fas fa-piggy-bank"></i>
            </div>
        </div>
        <div class="card">
            <div class="card-content">
                <div class="number">$68</div>
                <div class="card-name">Yearly balance</div>
            </div>
            <div class="icon-box">
                <i class="fas fa-balance-scale"></i>
            </div>
        </div>
        <div class="card">
            <div class="card-content">
                <div class="number">Rent</div>
                <div class="card-name">Main category</div>
            </div>
            <div class="icon-box">
                <i class="fas fa-list"></i>
            </div>
        </div>
    </div>
    <div class="charts">
        <div class="chart">
            <h2>Earnings (past 12 months)</h2>
            <div>
                <canvas id="lineChart"></canvas>
            </div>
        </div>
        <div class="chart doughnut-chart">
            <h2>Employees</h2>
            <div>
                <canvas id="doughnut"></canvas>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/delete-wallet.html
{% extends 'dashboard/wallet.html' %}

{% block content %}

<div class="main">
    <div class="transactions">
        {% if form.errors %}
        <div class="alert alert-danger">
            <strong>{{ form.errors }}</strong>
        </div>
        {% endif %}

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="wallet-choices">
            <h3>Do you wish to delete your wallet? This action is irreversible.</h3>
            <form method="POST" action="{% url 'manager:delete-wallet' %}">
                {% csrf_token %}
                <div class="wallet-form" id="delete-wallet">
                    <button type="submit" class="wallet-del-button">Delete</button>
                    <a href="{% url 'manager:wallet' %}" class="wallet-canc-button">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/transactions.html
{% extends 'dashboard/base.html' %}

{% block content%}
<div class="main">
    <div class="transactions">
        <div class="transaction-redirect">
            <a href="{% url "manager:add-transaction" %}">
                <div>Add a new transaction</div>
            </a>
        </div>
        <div class="generate-statement">
            <a href="{% url "manager:generate-statement" %}">
                <div>Generate statement</div>
            </a>
        </div>
        <div class="transactions-list">
            {% if transactions %}
                <h2>Transaction details</h2>
                <ul>
                    {% for transaction in transactions%}
                        <li>
                            <p> <strong> ID: </strong> {{ transaction.id }} </p>
                            <p> <strong> Date: </strong> {{ transaction.date }} </p>
                            <p> <strong> Value: </strong> {{ transaction.value }} </p>
                            <p> <strong> Description: </strong> {{ transaction.description }} </p>
                            <div class="delete-transaction">
                                <form class="delete-transaction-form" action="{% url 'manager:delete-transaction' %}" data-transaction-id="{{ transaction.id }}" method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="transaction-del-btn">Remove</button>
                                </form>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No transactions found.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/dashboard/update-wallet.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div class="main">
    <div class="wallet">
        <h1>Hello {{ user.username }}!</h1>
        
        {% if form.errors %}
        <div class="alert alert-danger">
            <strong>{{ form.errors }}</strong>
        </div>
        {% endif %}

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="wallet-form">
            <form class="w-form" method="post">
                {% csrf_token %}
                <h2>Update your wallet info here</h2>
                <div class="wallet-form">
                    <label for="currency">Currency:</label>
                    {{ form.currencyType }}
                </div>
                <div class="wallet-form">
                    <label for="income">Monthly Income:</label>
                    {{ form.monthlyIncome }}
                </div>
                <div class="wallet-form">
                    <label for="balance">Balance:</label>
                    {{ form.balance }}
                </div>
                <button type="submit">Update wallet</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/wallet.html
{% extends 'dashboard/base.html' %}

{% block content %}

<div class="main">
    <div class="wallet">
        <h1>Hello {{ user.username }}!</h1>
        
        {% if form.errors %}
        <div class="alert alert-danger">
            <strong>{{ form.errors }}</strong>
        </div>
        {% endif %}

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="wallet-choices">
            <ul>
                <li>
                    <a href="{% url "manager:create-wallet" %}">
                        <div>Create wallet</div>
                    </a>
                </li>
                <li>
                    <a href="{% url "manager:update-wallet" %}">
                        <div>Update wallet</div>
                    </a>
                </li>
                <li>
                    <a href="{% url "manager:delete-wallet" %}">
                        <div>Delete wallet</div>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>



{% endblock %}